#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Check changed files between frontend and backend

# If frontend has no changes, no need to run frontend lint-staged
if [ -n "$(git status packages/frontend --porcelain --untracked-files=no)" ]; then
  cd packages/frontend
  npx lint-staged
fi

# If backend has no changes, no need to run backend lint-staged
if [ -n "$(git status packages/backend --porcelain --untracked-files=no)" ]; then
  cd packages/backend
  npx lint-staged
fi
